import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";

const inter = Inter({ subsets: ["latin"] });

export const getStaticProps: GetStaticProps = async (ctx) => {
  const pizzaToppings = [
    "barbecue",
    "mushroom",
    "cheese",
    "suya",
    "pepperoni",
    "plantain",
  ];

  return {
    props: {
      pizzaToppings,
    },
  };
};

interface Props {
  pizzaToppings: string[];
}

const Pizza = ({ pizzaToppings }: Props) => {
  return (
    <>
      <Head>
        <title>Pizza Toppings</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {pizzaToppings.map((p) => (
            <div className="topping" key={p}>
              <h2 className={inter.className}>{p}</h2>

              <p className={inter.className}>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit
              </p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Pizza;
